package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;

import java.math.BigInteger;

/**
 * 系统用户权限表
 *
 */
@TableName("sj_system_user_permission")
public class SystemUserPermission extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, String> {


    private String groupName;

    private BigInteger systemUserId;

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }


    public BigInteger getSystemUserId() {
        return systemUserId;
    }

    public void setSystemUserId(BigInteger systemUserId) {
        this.systemUserId = systemUserId;
    }
}
