package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;
import com.old.silence.job.common.enums.ExpressionTypeEnum;
import com.old.silence.job.common.enums.FailStrategy;
import com.old.silence.job.common.enums.WorkflowNodeType;

import java.math.BigInteger;

/**
 * 工作流节点
 *
 */
@TableName("sj_workflow_node")
public class WorkflowNode extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, String> {


    /**
     * 节点名称
     */
    private String nodeName;

    /**
     * 组名称
     */
    private String groupName;

    /**
     * 任务信息id
     */
    private BigInteger jobId;

    /**
     * 工作流ID
     */
    private BigInteger workflowId;

    /**
     * 1、任务节点 2、条件节点 3、回调节点
     */
    private WorkflowNodeType nodeType;


    /**
     * 表达式类型
     */
    private ExpressionTypeEnum expressionType;

    /**
     * 失败策略 1、跳过 2、阻塞
     */
    private FailStrategy failStrategy;

    /**
     * 优先级
     */
    private Integer priorityLevel;


    /**
     * 节点信息
     */
    private String nodeInfo;

    /**
     * 工作流节点状态 0、关闭、1、开启
     */
    private Boolean workflowNodeStatus;

    /**
     * 版本号
     */
    private Integer version;

    /**
     * 扩展字段
     */
    private String extAttrs;

    @TableLogic
    @TableField(value = "is_deleted")
    private Boolean deleted;


    public String getNodeName() {
        return nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public BigInteger getJobId() {
        return jobId;
    }

    public void setJobId(BigInteger jobId) {
        this.jobId = jobId;
    }

    public BigInteger getWorkflowId() {
        return workflowId;
    }

    public void setWorkflowId(BigInteger workflowId) {
        this.workflowId = workflowId;
    }

    public WorkflowNodeType getNodeType() {
        return nodeType;
    }

    public void setNodeType(WorkflowNodeType nodeType) {
        this.nodeType = nodeType;
    }

    public ExpressionTypeEnum getExpressionType() {
        return expressionType;
    }

    public void setExpressionType(ExpressionTypeEnum expressionType) {
        this.expressionType = expressionType;
    }

    public FailStrategy getFailStrategy() {
        return failStrategy;
    }

    public void setFailStrategy(FailStrategy failStrategy) {
        this.failStrategy = failStrategy;
    }

    public Integer getPriorityLevel() {
        return priorityLevel;
    }

    public void setPriorityLevel(Integer priorityLevel) {
        this.priorityLevel = priorityLevel;
    }

    public String getNodeInfo() {
        return nodeInfo;
    }

    public void setNodeInfo(String nodeInfo) {
        this.nodeInfo = nodeInfo;
    }

    public Boolean getWorkflowNodeStatus() {
        return workflowNodeStatus;
    }

    public void setWorkflowNodeStatus(Boolean workflowNodeStatus) {
        this.workflowNodeStatus = workflowNodeStatus;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getExtAttrs() {
        return extAttrs;
    }

    public void setExtAttrs(String extAttrs) {
        this.extAttrs = extAttrs;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
